<?php
declare(strict_types = 1);

namespace Elasticsearch\Endpoints\Ml;

use Elasticsearch\Endpoints\AbstractEndpoint;

/**
 * Class OpenJob
 * Generated by util/GenerateEndpoints.php
 *
 * @category Elasticsearch
 * @package  Elasticsearch\Endpoints\Ml
 * @author   Enrico Zimuel <enrico.zimuel@elastic.co>
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache2
 * @link     http://elastic.co
 */
class OpenJob extends AbstractEndpoint
{
    public function getURI(): string
    {
        if (isset($this->job_id) !== true) {
            throw new Exceptions\RuntimeException(
                'job_id is required for open_job'
            );
        }
        $job_id = $this->job_id;
        $ignore_downtime = $this->ignore_downtime ?? null;
        $timeout = $this->timeout ?? null;

        return "/_xpack/ml/anomaly_detectors/$job_id/_open";
    }

    public function getParamWhitelist(): array
    {
        return [];
    }

    public function getMethod(): string
    {
        return 'POST';
    }
    
    public function setJobId($job_id): OpenJob
    {
        if (isset($job_id) !== true) {
            return $this;
        }
        $this->job_id = $job_id;

        return $this;
    }

    public function setIgnoreDowntime($ignore_downtime): OpenJob
    {
        if (isset($ignore_downtime) !== true) {
            return $this;
        }
        $this->ignore_downtime = $ignore_downtime;

        return $this;
    }

    public function setTimeout($timeout): OpenJob
    {
        if (isset($timeout) !== true) {
            return $this;
        }
        $this->timeout = $timeout;

        return $this;
    }

}
