<?php
declare(strict_types = 1);

namespace Elasticsearch\XPack\Endpoints\Security;

use Elasticsearch\Endpoints\AbstractEndpoint;

/**
 * Class GetRoleMapping
 * Generated by util/GenerateEndpoints.php
 *
 * @category Elasticsearch
 * @package  Elasticsearch\XPack\Endpoints\Security
 * @author   Enrico Zimuel <enrico.zimuel@elastic.co>
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache2
 * @link     http://elastic.co
 */
class GetRoleMapping extends AbstractEndpoint
{
    public function getURI(): string
    {
        $name = $this->name ?? null;

        if (isset($name)) {
            return "/_xpack/security/role_mapping/$name";
        }
        return "/_xpack/security/role_mapping";
    }

    public function getParamWhitelist(): array
    {
        return [
            
        ];
    }

    public function getMethod(): string
    {
        return 'GET';
    }
    
    public function setGetRoleMapping($name): GetRoleMapping
    {
        if (isset($name) !== true) {
            return $this;
        }
        $this->name = $name;

        return $this;
    }

}
